-- ============================================================
-- Schema & Seed para OTT - PostgreSQL (Docker Entrypoint)
-- ============================================================

-- 1. ESTRUCTURA DE TABLAS

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profiles (
    id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    region VARCHAR(30) NOT NULL,
    suscripcion VARCHAR(20) NOT NULL DEFAULT 'Sin plan',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    descripcion TEXT,
    categoria VARCHAR(50),
    region VARCHAR(30),
    video_url TEXT,
    imagen_url TEXT,
    hero_url TEXT,
    tipo VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    pelicula_id BIGINT REFERENCES movies(id) ON DELETE CASCADE,
    UNIQUE(usuario_id, pelicula_id)
);

CREATE TABLE IF NOT EXISTS watch_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    pelicula_id BIGINT REFERENCES movies(id) ON DELETE CASCADE,
    minuto INTEGER DEFAULT 0,
    UNIQUE(usuario_id, pelicula_id)
);

CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    pelicula_id BIGINT REFERENCES movies(id) ON DELETE CASCADE,
    valor INTEGER NOT NULL,
    UNIQUE(usuario_id, pelicula_id)
);

-- 2. DATOS SEMILLA (USUARIOS Y PERFILES)
-- Passwords hasheadas con bcrypt:
-- admin@ott.com -> admin123
-- demo@ott.com  -> demo123

INSERT INTO users (id, email, password_hash) VALUES
(1, 'admin@ott.com', '$2b$12$54DB9tOt6iTkVIV/A3YpSOnzpdVilXkPk.ojOfa4Z7KGOGs3b/dyW'),
(2, 'demo@ott.com', '$2b$12$CtKFfpe8OIeIzFuOKnDeu.q.Hv4UBbG3Ny9ChJXKhlLTr3fJhHV/W')
ON CONFLICT (email) DO NOTHING;

SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));

INSERT INTO profiles (id, nombre, region, suscripcion) VALUES
(1, 'Admin MUBI', 'LATAM', 'Premium'),
(2, 'Cinéfilo Demo', 'LATAM', 'Basica')
ON CONFLICT (id) DO NOTHING;

-- 3. CATÁLOGO DE PELÍCULAS Y SERIES (20 TÍTULOS)

INSERT INTO movies (id, titulo, descripcion, categoria, region, imagen_url, video_url, hero_url, tipo) VALUES
(1, 'Monos', 'En una remota montaña, ocho adolescentes armados custodian a una rehén estadounidense y una vaca lechera mientras sobreviven al aislamiento.', 'Drama, Cine Colombiano', 'LATAM', '/static/images/posters/monos.jpg', '/static/videos/monos.mp4', '/static/images/posters/monos.jpg', 'Película'),
(2, 'El olvido que seremos', 'Relata la vida de Héctor Abad Gómez, un destacado médico colombiano y activista por los derechos humanos en Medellín.', 'Drama, Cine Colombiano', 'LATAM', '/static/images/posters/el_olvido_que_seremos.jpg', '/static/videos/el_olvido_que_seremos.mp4', '/static/images/posters/el_olvido_que_seremos.jpg', 'Película'),
(3, 'La vendedora de rosas', 'Mónica, una niña que vive en las calles de Medellín, intenta sobrevivir vendiendo rosas durante la noche de Navidad.', 'Drama, Cine Colombiano', 'LATAM', '/static/images/posters/la_vendedora_de_rosas.jpg', '/static/videos/la_vendedora_de_rosas.mp4', '/static/images/posters/la_vendedora_de_rosas.jpg', 'Película'),
(4, 'Pájaros de verano', 'Durante la bonanza marimbera en Colombia, una familia wayuu se ve atrapada en una sangrienta guerra por el control del narcotráfico.', 'Drama, Cine Colombiano', 'LATAM', '/static/images/posters/pajaros_de_verano.jpg', '/static/videos/pajaros_de_verano.mp4', '/static/images/posters/pajaros_de_verano.jpg', 'Película'),
(5, 'El páramo', 'Un comando especial es enviado a una base militar aislada en un páramo desolado en busca de respuestas.', 'Terror, Cine Colombiano', 'LATAM', '/static/images/posters/el_paramo.jpg', '/static/videos/el_paramo.mp4', '/static/images/posters/el_paramo.jpg', 'Película'),
(6, 'Roma', 'Retrato íntimo y conmovedor de la vida de una familia y su empleada doméstica en el México de los años 70.', 'Drama, Cine Independiente', 'LATAM', '/static/images/posters/roma.jpg', '/static/videos/roma.mp4', '/static/images/posters/roma.jpg', 'Película'),
(7, 'Narcos', 'La cruda crónica del auge y caída de los principales carteles de narcotráfico y su lucha contra las autoridades.', 'Crimen, Drama, Suspenso', 'LATAM', '/static/images/posters/narcos.jpg', '/static/videos/narcos.mp4', '/static/images/posters/narcos.jpg', 'Serie'),
(8, 'A través de mi ventana', 'La atracción de Raquel hacia su misterioso vecino Ares se convierte en una apasionada e intensa historia.', 'Romance, Drama', 'LATAM', '/static/images/posters/a_traves_de_mi_ventana.jpg', '/static/videos/a_traves_de_mi_ventana.mp4', '/static/images/posters/a_traves_de_mi_ventana.jpg', 'Película'),
(9, 'La casa de papel', 'Un grupo de atracadores guiados por ''El Profesor'' ejecuta el asalto más ambicioso a la Fábrica Nacional de Moneda.', 'Acción, Suspenso', 'EUROPA', '/static/images/posters/la_casa_de_papel.jpg', '/static/videos/la_casa_de_papel.mp4', '/static/images/posters/la_casa_de_papel.jpg', 'Serie'),
(10, 'Dark', 'La desaparición de dos niños en Winden desvela un intrincado misterio temporal que une a cuatro familias.', 'Ciencia Ficción, Suspenso', 'EUROPA', '/static/images/posters/dark.jpg', '/static/videos/dark.mp4', '/static/images/posters/dark.jpg', 'Serie'),
(11, 'Peaky Blinders', 'En el Birmingham de entreguerras, Thomas Shelby dirige a una sanguinaria banda dispuesta a llegar a la cima del poder.', 'Drama, Crimen', 'EUROPA', '/static/images/posters/peaky_blinders.jpg', '/static/videos/peaky_blinders.mp4', '/static/images/posters/peaky_blinders.jpg', 'Serie'),
(12, 'Sherlock', 'El legendario detective Sherlock Holmes resuelve los crímenes más intrincados en el Londres actual.', 'Misterio, Suspenso', 'EUROPA', '/static/images/posters/sherlock.jpg', '/static/videos/sherlock.mp4', '/static/images/posters/sherlock.jpg', 'Serie'),
(13, 'El laberinto del fauno', 'En la España de la posguerra, una niña descubre un mundo mágico y oscuro que pondrá a prueba su valor.', 'Fantasía, Drama', 'EUROPA', '/static/images/posters/el_laberinto_del_fauno.jpg', '/static/videos/el_laberinto_del_fauno.mp4', '/static/images/posters/el_laberinto_del_fauno.jpg', 'Película'),
(14, 'Avatar', 'Un marine parapléjico enviado a la luna Pandora debe decidir entre cumplir su misión o proteger a la civilización Na''vi.', 'Ciencia Ficción, Acción', 'USA', '/static/images/posters/avatar.jpg', '/static/videos/avatar.mp4', '/static/images/posters/avatar.jpg', 'Película'),
(15, 'Interestelar', 'Ante la extinción de la Tierra, un grupo de exploradores viaja a través de un agujero de gusano para salvar a la humanidad.', 'Ciencia Ficción, Aventura', 'USA', '/static/images/posters/interestelar.jpg', '/static/videos/interestelar.mp4', '/static/images/posters/interestelar.jpg', 'Película'),
(16, 'Forrest Gump', 'Las extraordinarias vivencias de un hombre inocente con un corazón bondadoso que atraviesa las décadas clave de EE.UU.', 'Drama, Comedia', 'USA', '/static/images/posters/forrest_gump.jpg', '/static/videos/forrest_gump.mp4', '/static/images/posters/forrest_gump.jpg', 'Película'),
(17, 'John Wick', 'Un implacable exasesino vuelve al bajo mundo criminal cuando le arrebatan el último regalo de su difunta esposa.', 'Acción, Suspenso', 'USA', '/static/images/posters/john_wick.jpg', '/static/videos/john_wick.mp4', '/static/images/posters/john_wick.jpg', 'Película'),
(18, 'Breaking Bad', 'Walter White, profesor de química con cáncer terminal, entra al negocio de la metanfetamina para asegurar a su familia.', 'Drama, Crimen', 'USA', '/static/images/posters/breaking_bad.jpg', '/static/videos/breaking_bad.mp4', '/static/images/posters/breaking_bad.jpg', 'Serie'),
(19, 'Toy Story', 'El vaquero Woody y el astronauta Buzz Lightyear compiten por el afecto de Andy antes de forjar una amistad inseparable.', 'Animación, Familiar', 'USA', '/static/images/posters/toy_story.jpg', '/static/videos/toy_story.mp4', '/static/images/posters/toy_story.jpg', 'Película'),
(20, 'Hasta el último hombre', 'La inspiradora historia de Desmond Doss, un soldado que salvó a 75 compañeros en la sangrienta batalla de Okinawa sin disparar un arma.', 'Bélico, Drama, Acción', 'USA', '/static/images/posters/hacksaw_ridge.jpg', '/static/videos/hacksaw_ridge.mp4', '/static/images/posters/hacksaw_ridge.jpg', 'Película')
ON CONFLICT (id) DO NOTHING;

-- 4. DATOS SEMILLA (FAVORITOS, RATINGS, HISTORIAL)

-- Favoritos del usuario demo (id 2)
INSERT INTO favorites (usuario_id, pelicula_id) VALUES
(2, 1),
(2, 2),
(2, 6),
(2, 15)
ON CONFLICT (usuario_id, pelicula_id) DO NOTHING;

-- Calificaciones (Likes = 1, Dislikes = -1)
INSERT INTO ratings (usuario_id, pelicula_id, valor) VALUES
(1, 1, 1),
(2, 1, 1),
(1, 2, 1),
(2, 6, 1),
(1, 18, 1),
(2, 18, 1),
(2, 15, 1),
(2, 8, -1)
ON CONFLICT (usuario_id, pelicula_id) DO NOTHING;

-- Historial de visualización
INSERT INTO watch_history (usuario_id, pelicula_id, minuto) VALUES
(2, 1, 45),
(2, 15, 120),
(1, 18, 90)
ON CONFLICT (usuario_id, pelicula_id) DO NOTHING;
